title: Leting Zhang
description: >-
  Assistant Professor of Management Information Systems,
  Alfred Lerner College of Business & Economics, University of Delaware
url: "https://letingz.github.io"
baseurl: ""
lang: en-US

theme: jekyll-theme-minimal

author:
  name: Leting Zhang
  email: letingz@udel.edu

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - docs/
  - vendor/
