title: Leting Zhang
description: >-
  Assistant Professor of Management Information Systems,
  Alfred Lerner College of Business & Economics, University of Delaware
url: "https://letingz.github.io"
baseurl: ""
lang: en-US

theme: jekyll-theme-minimal

author:
  name: Leting Zhang
  email: letingz@udel.edu
  googlescholar: "https://scholar.google.com/citations?hl=en&user=dUXnG4wAAAAJ"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from

exclude:
  - .jekyll-cache/
  - .sass-cache/
  - node_modules/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - docs/
  - vendor/
